#!/usr/bin/env python

import subprocess

binomial_script = './Binomial'

def check_err(output, correct_output, test_name, tolerance=0.000001):
    if abs(output - correct_output) > tolerance:
        raise Exception('%s test failed: %.5f should be closer to %.5f'%(test_name, 
            output, correct_output))

correct_output = {
    'exact':[
        (0.55085, 0.00002), 
        (0.10657, 0.00002), 
        (0.01279, 0.00002),
    ],
    'sample':[
        (0.55085, 0.05956), 
        (0.10657, 0.03188), 
        (0.01279, 0.01136),
    ],
    'chebyshev':[
        (1.0, 0.00002), 
        (0.5, 0.00002), 
        (0.1, 0.00002),
    ]
}

for experiment_type in ['exact', 'sample', 'chebyshev']:
    ### Test sampling computation cases ###
    output = float(subprocess.check_output([binomial_script,
        '-t',experiment_type,
        '-n','30',
        '-p','0.5',
        '-m','10000',
        '-l','10',
        '-u','15'
    ]))
    correct, tolerance = correct_output[experiment_type][0]
    check_err(output, correct, experiment_type, tolerance=tolerance)
    
    output = float(subprocess.check_output([binomial_script,
        '-t',experiment_type,
        '-n','50',
        '-p','0.1',
        '-m','10000',
        '-l','1',
        '-u','2'
    ]))
    correct, tolerance = correct_output[experiment_type][1]
    check_err(output, correct, experiment_type, tolerance=tolerance)
    
    output = float(subprocess.check_output([binomial_script,
        '-t',experiment_type,
        '-n','10',
        '-p','0.9',
        '-m','10000',
        '-l','4',
        '-u','6'
    ]))
    correct, tolerance = correct_output[experiment_type][2]
    check_err(output, correct, experiment_type, tolerance=tolerance)
